#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp
mount -t debugfs none /sys/kernel/debug
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

if [ -x /root/@POC@ ]; then
    echo "execute /root/@POC@..."
    /root/@POC@
else
    echo "cannot find /root/@POC@"
fi

setsid cttyhack setuidgid 0 sh

poweroff -d 0  -f
